#ifndef RUNTIMECONFIG_H
#define RUNTIMECONFIG_H

#include <QString>
#include <string>
#include <QJsonObject>
#include "config.h"
/** 由 config.json 填充；存储在 RuntimeConfig.cpp，对外只读（getter + 宏）。
 *  命令行覆盖见 RuntimeConfig_private.h（仅 GlobalVariate.cpp 可包含）。 */

int RuntimeConfig_GAME_LOSE_SEC();
#define GAME_LOSE_SEC (RuntimeConfig_GAME_LOSE_SEC())

bool RuntimeConfig_IsExamining();
#define IsExamining (RuntimeConfig_IsExamining())

int RuntimeConfig_TimePerFrame();
#define TimePerFrame (RuntimeConfig_TimePerFrame())

bool RuntimeConfig_EditorMode();
#define EditorMode (RuntimeConfig_EditorMode())

bool RuntimeConfig_GlobalVision();
#define GlobalVision (RuntimeConfig_GlobalVision())

bool RuntimeConfig_only_debug_Player0();
#define only_debug_Player0 (RuntimeConfig_only_debug_Player0())

bool RuntimeConfig_filterRepetitionMessage();
#define filterRepetitionMessage (RuntimeConfig_filterRepetitionMessage())

int RuntimeConfig_GAME_WIDTH();
#define GAME_WIDTH (RuntimeConfig_GAME_WIDTH())

int RuntimeConfig_GAME_HEIGHT();
#define GAME_HEIGHT (RuntimeConfig_GAME_HEIGHT())

std::string RuntimeConfig_GAME_VERSION();
#define GAME_VERSION (RuntimeConfig_GAME_VERSION())

QString RuntimeConfig_GAME_TITLE();
#define GAME_TITLE (RuntimeConfig_GAME_TITLE())

std::string RuntimeConfig_MAPFILE_SUFFIX();
#define MAPFILE_SUFFIX (RuntimeConfig_MAPFILE_SUFFIX())

QString RuntimeConfig_FixedMapFile();

int RuntimeConfig_MapRotationDegrees();

int RuntimeConfig_MAXPLAYER();
#define MAXPLAYER (RuntimeConfig_MAXPLAYER())

int RuntimeConfig_NOWPLAYER();
#define NOWPLAYER (RuntimeConfig_NOWPLAYER())

int RuntimeConfig_NOWPLAYERREPRESENT();
#define NOWPLAYERREPRESENT (RuntimeConfig_NOWPLAYERREPRESENT())

int RuntimeConfig_INITIAL_FREQUENCY();
#define INITIAL_FREQUENCY (RuntimeConfig_INITIAL_FREQUENCY())

int RuntimeConfig_MEMORYROW();
#define MEMORYROW (RuntimeConfig_MEMORYROW())

int RuntimeConfig_MEMORYCOLUMN();
#define MEMORYCOLUMN (RuntimeConfig_MEMORYCOLUMN())

int RuntimeConfig_GAMEWIDGET_WIDTH();
#define GAMEWIDGET_WIDTH (RuntimeConfig_GAMEWIDGET_WIDTH())

int RuntimeConfig_GAMEWIDGET_HEIGHT();
#define GAMEWIDGET_HEIGHT (RuntimeConfig_GAMEWIDGET_HEIGHT())

Double RuntimeConfig_BLOCKSIDELENGTH();
#define BLOCKSIDELENGTH (RuntimeConfig_BLOCKSIDELENGTH())

int RuntimeConfig_UNLOAD_RADIAN();
#define UNLOAD_RADIAN (RuntimeConfig_UNLOAD_RADIAN())

int RuntimeConfig_MAP_L();
#define MAP_L (RuntimeConfig_MAP_L())

int RuntimeConfig_MAP_U();
#define MAP_U (RuntimeConfig_MAP_U())

Double RuntimeConfig_HUMAN_SPEED();
#define HUMAN_SPEED (RuntimeConfig_HUMAN_SPEED())

Double RuntimeConfig_WOOD_BOAT_SPEED();
#define WOOD_BOAT_SPEED (RuntimeConfig_WOOD_BOAT_SPEED())

Double RuntimeConfig_ANIMAL_SPEED();
#define ANIMAL_SPEED (RuntimeConfig_ANIMAL_SPEED())

QString RuntimeConfig_RESPATH();
#define RESPATH (RuntimeConfig_RESPATH())

bool RuntimeConfig_OPTION_MUSIC();
#define OPTION_MUSIC (RuntimeConfig_OPTION_MUSIC())

bool RuntimeConfig_OPTION_SOUND();
#define OPTION_SOUND (RuntimeConfig_OPTION_SOUND())

bool RuntimeConfig_OPTION_SELECT();
#define OPTION_SELECT (RuntimeConfig_OPTION_SELECT())

bool RuntimeConfig_OPTION_LINE();
#define OPTION_LINE (RuntimeConfig_OPTION_LINE())

bool RuntimeConfig_OPTION_POS();
#define OPTION_POS (RuntimeConfig_OPTION_POS())

bool RuntimeConfig_OPTION_OVERLAP();
#define OPTION_OVERLAP (RuntimeConfig_OPTION_OVERLAP())

Double RuntimeConfig_BUILDING_BLOOD_FIRE_SMALL();
#define BUILDING_BLOOD_FIRE_SMALL (RuntimeConfig_BUILDING_BLOOD_FIRE_SMALL())

Double RuntimeConfig_BUILDING_BLOOD_FIRE_MIDDLE();
#define BUILDING_BLOOD_FIRE_MIDDLE (RuntimeConfig_BUILDING_BLOOD_FIRE_MIDDLE())

Double RuntimeConfig_BUILDING_BLOOD_FIRE_BIG();
#define BUILDING_BLOOD_FIRE_BIG (RuntimeConfig_BUILDING_BLOOD_FIRE_BIG())

int RuntimeConfig_HOUSE_HUMAN_NUM();
#define HOUSE_HUMAN_NUM (RuntimeConfig_HOUSE_HUMAN_NUM())

int RuntimeConfig_VISION_GAZELLE();
#define VISION_GAZELLE (RuntimeConfig_VISION_GAZELLE())

int RuntimeConfig_BLOOD_GAZELLE();
#define BLOOD_GAZELLE (RuntimeConfig_BLOOD_GAZELLE())

int RuntimeConfig_CNT_GAZELLE();
#define CNT_GAZELLE (RuntimeConfig_CNT_GAZELLE())

int RuntimeConfig_VISION_LION();
#define VISION_LION (RuntimeConfig_VISION_LION())

int RuntimeConfig_BLOOD_LION();
#define BLOOD_LION (RuntimeConfig_BLOOD_LION())

int RuntimeConfig_CNT_LION();
#define CNT_LION (RuntimeConfig_CNT_LION())

int RuntimeConfig_ANIMAL_ATTACKRANGE_LION();
#define ANIMAL_ATTACKRANGE_LION (RuntimeConfig_ANIMAL_ATTACKRANGE_LION())

int RuntimeConfig_VISION_ELEPHANT();
#define VISION_ELEPHANT (RuntimeConfig_VISION_ELEPHANT())

int RuntimeConfig_BLOOD_ELEPHANT();
#define BLOOD_ELEPHANT (RuntimeConfig_BLOOD_ELEPHANT())

Double RuntimeConfig_SPEED_ELEPHANT();
#define SPEED_ELEPHANT (RuntimeConfig_SPEED_ELEPHANT())

int RuntimeConfig_CNT_ELEPHANT();
#define CNT_ELEPHANT (RuntimeConfig_CNT_ELEPHANT())

int RuntimeConfig_ANIMAL_ATTACKRANGE_ELEPHANT();
#define ANIMAL_ATTACKRANGE_ELEPHANT (RuntimeConfig_ANIMAL_ATTACKRANGE_ELEPHANT())

int RuntimeConfig_BLOOD_TREE();
#define BLOOD_TREE (RuntimeConfig_BLOOD_TREE())

int RuntimeConfig_CNT_TREE();
#define CNT_TREE (RuntimeConfig_CNT_TREE())

int RuntimeConfig_VISION_FARMER();
#define VISION_FARMER (RuntimeConfig_VISION_FARMER())

int RuntimeConfig_BLOOD_FARMER();
#define BLOOD_FARMER (RuntimeConfig_BLOOD_FARMER())

int RuntimeConfig_DIS_FARMER_HUNT();
#define DIS_FARMER_HUNT (RuntimeConfig_DIS_FARMER_HUNT())

int RuntimeConfig_FARMER_CARRYLIMIT_WOOD();
#define FARMER_CARRYLIMIT_WOOD (RuntimeConfig_FARMER_CARRYLIMIT_WOOD())

int RuntimeConfig_FARMER_CARRYLIMIT_FOOD();
#define FARMER_CARRYLIMIT_FOOD (RuntimeConfig_FARMER_CARRYLIMIT_FOOD())

int RuntimeConfig_FARMER_CARRYLIMIT_GOLD();
#define FARMER_CARRYLIMIT_GOLD (RuntimeConfig_FARMER_CARRYLIMIT_GOLD())

int RuntimeConfig_FARMER_CARRYLIMIT_STONE();
#define FARMER_CARRYLIMIT_STONE (RuntimeConfig_FARMER_CARRYLIMIT_STONE())

int RuntimeConfig_FARMER_CARRYLIMIT_UPGRADEWOOD();
#define FARMER_CARRYLIMIT_UPGRADEWOOD (RuntimeConfig_FARMER_CARRYLIMIT_UPGRADEWOOD())

int RuntimeConfig_FARMER_CARRYLIMIT_UPGRADEFOOD();
#define FARMER_CARRYLIMIT_UPGRADEFOOD (RuntimeConfig_FARMER_CARRYLIMIT_UPGRADEFOOD())

int RuntimeConfig_FARMER_CARRYLIMIT_UPGRADEGOLD();
#define FARMER_CARRYLIMIT_UPGRADEGOLD (RuntimeConfig_FARMER_CARRYLIMIT_UPGRADEGOLD())

int RuntimeConfig_FARMER_CARRYLIMIT_UPGRADESTONE();
#define FARMER_CARRYLIMIT_UPGRADESTONE (RuntimeConfig_FARMER_CARRYLIMIT_UPGRADESTONE())

Double RuntimeConfig_FARMER_GATHERSPEED_WOOD();
#define FARMER_GATHERSPEED_WOOD (RuntimeConfig_FARMER_GATHERSPEED_WOOD())

Double RuntimeConfig_FARMER_GATHERSPEED_FOOD();
#define FARMER_GATHERSPEED_FOOD (RuntimeConfig_FARMER_GATHERSPEED_FOOD())

Double RuntimeConfig_FARMER_GATHERSPEED_GOLD();
#define FARMER_GATHERSPEED_GOLD (RuntimeConfig_FARMER_GATHERSPEED_GOLD())

Double RuntimeConfig_FARMER_GATHERSPEED_STONE();
#define FARMER_GATHERSPEED_STONE (RuntimeConfig_FARMER_GATHERSPEED_STONE())

Double RuntimeConfig_FARMER_CONSTRUCTSPEED();
#define FARMER_CONSTRUCTSPEED (RuntimeConfig_FARMER_CONSTRUCTSPEED())

Double RuntimeConfig_REPAIR_COST_RATIO();
#define REPAIR_COST_RATIO (RuntimeConfig_REPAIR_COST_RATIO())

int RuntimeConfig_CNT_UPGRADEFARM();
#define CNT_UPGRADEFARM (RuntimeConfig_CNT_UPGRADEFARM())

int RuntimeConfig_CNT_BUSH();
#define CNT_BUSH (RuntimeConfig_CNT_BUSH())

int RuntimeConfig_CNT_STONE();
#define CNT_STONE (RuntimeConfig_CNT_STONE())

int RuntimeConfig_CNT_GOLDORE();
#define CNT_GOLDORE (RuntimeConfig_CNT_GOLDORE())

int RuntimeConfig_CNT_FISH();
#define CNT_FISH (RuntimeConfig_CNT_FISH())

bool RuntimeConfig_MAP_EXPLORE();
#define MAP_EXPLORE (RuntimeConfig_MAP_EXPLORE())

bool RuntimeConfig_MAP_VISIABLE();
#define MAP_VISIABLE (RuntimeConfig_MAP_VISIABLE())

int RuntimeConfig_INITIAL_WOOD();
#define INITIAL_WOOD (RuntimeConfig_INITIAL_WOOD())

int RuntimeConfig_INITIAL_MEAT();
#define INITIAL_MEAT (RuntimeConfig_INITIAL_MEAT())

int RuntimeConfig_INITIAL_GOLD();
#define INITIAL_GOLD (RuntimeConfig_INITIAL_GOLD())

int RuntimeConfig_INITIAL_STONE();
#define INITIAL_STONE (RuntimeConfig_INITIAL_STONE())

Double RuntimeConfig_CRASHBOX_MICRO();
#define CRASHBOX_MICRO (RuntimeConfig_CRASHBOX_MICRO())

Double RuntimeConfig_CRASHBOX_SINGLEBLOCK();
#define CRASHBOX_SINGLEBLOCK (RuntimeConfig_CRASHBOX_SINGLEBLOCK())

Double RuntimeConfig_CRASHBOX_SMALLBLOCK();
#define CRASHBOX_SMALLBLOCK (RuntimeConfig_CRASHBOX_SMALLBLOCK())

Double RuntimeConfig_CRASHBOX_SMALL();
#define CRASHBOX_SMALL (RuntimeConfig_CRASHBOX_SMALL())

Double RuntimeConfig_CRASHBOX_MIDDLE();
#define CRASHBOX_MIDDLE (RuntimeConfig_CRASHBOX_MIDDLE())

Double RuntimeConfig_CRASHBOX_BIG();
#define CRASHBOX_BIG (RuntimeConfig_CRASHBOX_BIG())

Double RuntimeConfig_CRASHBOX_SINGLEOB();
#define CRASHBOX_SINGLEOB (RuntimeConfig_CRASHBOX_SINGLEOB())

Double RuntimeConfig_CRASHBOX_SMALLOB();
#define CRASHBOX_SMALLOB (RuntimeConfig_CRASHBOX_SMALLOB())

Double RuntimeConfig_CRASHBOX_BIGOB();
#define CRASHBOX_BIGOB (RuntimeConfig_CRASHBOX_BIGOB())

int RuntimeConfig_BLOOD_BUILD_CENTER();
#define BLOOD_BUILD_CENTER (RuntimeConfig_BLOOD_BUILD_CENTER())

int RuntimeConfig_VISION_CENTER();
#define VISION_CENTER (RuntimeConfig_VISION_CENTER())

int RuntimeConfig_BUILD_CENTER_WOOD();
#define BUILD_CENTER_WOOD (RuntimeConfig_BUILD_CENTER_WOOD())

int RuntimeConfig_TIME_BUILD_CENTER();
#define TIME_BUILD_CENTER (RuntimeConfig_TIME_BUILD_CENTER())

int RuntimeConfig_BUILDING_CENTER_CREATEFARMER_FOOD();
#define BUILDING_CENTER_CREATEFARMER_FOOD (RuntimeConfig_BUILDING_CENTER_CREATEFARMER_FOOD())

int RuntimeConfig_TIME_BUILDING_CENTER_CREATEFARMER();
#define TIME_BUILDING_CENTER_CREATEFARMER (RuntimeConfig_TIME_BUILDING_CENTER_CREATEFARMER())

int RuntimeConfig_BUILDING_CENTER_UPGRADE_TOOLAGE_FOOD();
#define BUILDING_CENTER_UPGRADE_TOOLAGE_FOOD (RuntimeConfig_BUILDING_CENTER_UPGRADE_TOOLAGE_FOOD())

int RuntimeConfig_TIME_BUILDING_CENTER_UPGRADE();
#define TIME_BUILDING_CENTER_UPGRADE (RuntimeConfig_TIME_BUILDING_CENTER_UPGRADE())

int RuntimeConfig_BUILDING_CENTER_UPGRADE_BRONZEAGE_FOOD();
#define BUILDING_CENTER_UPGRADE_BRONZEAGE_FOOD (RuntimeConfig_BUILDING_CENTER_UPGRADE_BRONZEAGE_FOOD())

int RuntimeConfig_BUILDING_CENTER_UPGRADE_BRONZEAGE_GOLD();
#define BUILDING_CENTER_UPGRADE_BRONZEAGE_GOLD (RuntimeConfig_BUILDING_CENTER_UPGRADE_BRONZEAGE_GOLD())

int RuntimeConfig_BLOOD_BUILD_HOUSE();
#define BLOOD_BUILD_HOUSE (RuntimeConfig_BLOOD_BUILD_HOUSE())

int RuntimeConfig_VISION_HOME();
#define VISION_HOME (RuntimeConfig_VISION_HOME())

int RuntimeConfig_BUILD_HOUSE_WOOD();
#define BUILD_HOUSE_WOOD (RuntimeConfig_BUILD_HOUSE_WOOD())

int RuntimeConfig_TIME_BUILD_HOME();
#define TIME_BUILD_HOME (RuntimeConfig_TIME_BUILD_HOME())

int RuntimeConfig_BLOOD_BUILD_STOCK();
#define BLOOD_BUILD_STOCK (RuntimeConfig_BLOOD_BUILD_STOCK())

int RuntimeConfig_VISION_STOCK();
#define VISION_STOCK (RuntimeConfig_VISION_STOCK())

int RuntimeConfig_BUILD_STOCK_WOOD();
#define BUILD_STOCK_WOOD (RuntimeConfig_BUILD_STOCK_WOOD())

int RuntimeConfig_TIME_BUILD_STOCK();
#define TIME_BUILD_STOCK (RuntimeConfig_TIME_BUILD_STOCK())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_CLOSER_ATTACK_FOOD();
#define BUILDING_STOCK_UPGRADE_CLOSER_ATTACK_FOOD (RuntimeConfig_BUILDING_STOCK_UPGRADE_CLOSER_ATTACK_FOOD())

int RuntimeConfig_TIME_BUILDING_STOCK_UPGRADE_CLOSER_ATTACK();
#define TIME_BUILDING_STOCK_UPGRADE_CLOSER_ATTACK (RuntimeConfig_TIME_BUILDING_STOCK_UPGRADE_CLOSER_ATTACK())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_CLOSER_ATTACK_ADDITION_ATTACK();
#define BUILDING_STOCK_UPGRADE_CLOSER_ATTACK_ADDITION_ATTACK (RuntimeConfig_BUILDING_STOCK_UPGRADE_CLOSER_ATTACK_ADDITION_ATTACK())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_CLOSER_ATTACK_2_FOOD();
#define BUILDING_STOCK_UPGRADE_CLOSER_ATTACK_2_FOOD (RuntimeConfig_BUILDING_STOCK_UPGRADE_CLOSER_ATTACK_2_FOOD())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_CLOSER_ATTACK_2_GOLD();
#define BUILDING_STOCK_UPGRADE_CLOSER_ATTACK_2_GOLD (RuntimeConfig_BUILDING_STOCK_UPGRADE_CLOSER_ATTACK_2_GOLD())

int RuntimeConfig_TIME_BUILDING_STOCK_UPGRADE_CLOSER_ATTACK_2();
#define TIME_BUILDING_STOCK_UPGRADE_CLOSER_ATTACK_2 (RuntimeConfig_TIME_BUILDING_STOCK_UPGRADE_CLOSER_ATTACK_2())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_CLOSER_ATTACK_2_ADDITION_ATTACK();
#define BUILDING_STOCK_UPGRADE_CLOSER_ATTACK_2_ADDITION_ATTACK (RuntimeConfig_BUILDING_STOCK_UPGRADE_CLOSER_ATTACK_2_ADDITION_ATTACK())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_INFANTRY_FOOD();
#define BUILDING_STOCK_UPGRADE_DEFENSE_INFANTRY_FOOD (RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_INFANTRY_FOOD())

int RuntimeConfig_TIME_BUILDING_STOCK_UPGRADE_DEFENSE_INFANTRY();
#define TIME_BUILDING_STOCK_UPGRADE_DEFENSE_INFANTRY (RuntimeConfig_TIME_BUILDING_STOCK_UPGRADE_DEFENSE_INFANTRY())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_INFANTRY_ADDITION_DEFENSE_INFANTRY();
#define BUILDING_STOCK_UPGRADE_DEFENSE_INFANTRY_ADDITION_DEFENSE_INFANTRY (RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_INFANTRY_ADDITION_DEFENSE_INFANTRY())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_INFANTRY_2_FOOD();
#define BUILDING_STOCK_UPGRADE_DEFENSE_INFANTRY_2_FOOD (RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_INFANTRY_2_FOOD())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_INFANTRY_2_GOLD();
#define BUILDING_STOCK_UPGRADE_DEFENSE_INFANTRY_2_GOLD (RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_INFANTRY_2_GOLD())

int RuntimeConfig_TIME_BUILDING_STOCK_UPGRADE_DEFENSE_INFANTRY_2();
#define TIME_BUILDING_STOCK_UPGRADE_DEFENSE_INFANTRY_2 (RuntimeConfig_TIME_BUILDING_STOCK_UPGRADE_DEFENSE_INFANTRY_2())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_INFANTRY_2_ADDITION_DEFENSE_INFANTRY();
#define BUILDING_STOCK_UPGRADE_DEFENSE_INFANTRY_2_ADDITION_DEFENSE_INFANTRY (RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_INFANTRY_2_ADDITION_DEFENSE_INFANTRY())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_MISSILE_DEFENSE_INFANTRY_FOOD();
#define BUILDING_STOCK_UPGRADE_MISSILE_DEFENSE_INFANTRY_FOOD (RuntimeConfig_BUILDING_STOCK_UPGRADE_MISSILE_DEFENSE_INFANTRY_FOOD())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_MISSILE_DEFENSE_INFANTRY_GOLD();
#define BUILDING_STOCK_UPGRADE_MISSILE_DEFENSE_INFANTRY_GOLD (RuntimeConfig_BUILDING_STOCK_UPGRADE_MISSILE_DEFENSE_INFANTRY_GOLD())

int RuntimeConfig_TIME_BUILDING_STOCK_UPGRADE_MISSILE_DEFENSE_INFANTRY();
#define TIME_BUILDING_STOCK_UPGRADE_MISSILE_DEFENSE_INFANTRY (RuntimeConfig_TIME_BUILDING_STOCK_UPGRADE_MISSILE_DEFENSE_INFANTRY())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_MISSILE_DEFENSE_INFANTRY_ADDITION_DEFENSE_INFANTRY();
#define BUILDING_STOCK_UPGRADE_MISSILE_DEFENSE_INFANTRY_ADDITION_DEFENSE_INFANTRY (RuntimeConfig_BUILDING_STOCK_UPGRADE_MISSILE_DEFENSE_INFANTRY_ADDITION_DEFENSE_INFANTRY())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_ARCHER_FOOD();
#define BUILDING_STOCK_UPGRADE_DEFENSE_ARCHER_FOOD (RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_ARCHER_FOOD())

int RuntimeConfig_TIME_BUILDING_STOCK_UPGRADE_DEFENSE_ARCHER();
#define TIME_BUILDING_STOCK_UPGRADE_DEFENSE_ARCHER (RuntimeConfig_TIME_BUILDING_STOCK_UPGRADE_DEFENSE_ARCHER())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_ARCHER_ADDITION_DEFENSE_ARCHER();
#define BUILDING_STOCK_UPGRADE_DEFENSE_ARCHER_ADDITION_DEFENSE_ARCHER (RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_ARCHER_ADDITION_DEFENSE_ARCHER())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_ARCHER_2_FOOD();
#define BUILDING_STOCK_UPGRADE_DEFENSE_ARCHER_2_FOOD (RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_ARCHER_2_FOOD())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_ARCHER_2_GOLD();
#define BUILDING_STOCK_UPGRADE_DEFENSE_ARCHER_2_GOLD (RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_ARCHER_2_GOLD())

int RuntimeConfig_TIME_BUILDING_STOCK_UPGRADE_DEFENSE_ARCHER_2();
#define TIME_BUILDING_STOCK_UPGRADE_DEFENSE_ARCHER_2 (RuntimeConfig_TIME_BUILDING_STOCK_UPGRADE_DEFENSE_ARCHER_2())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_ARCHER_2_ADDITION_DEFENSE_ARCHER();
#define BUILDING_STOCK_UPGRADE_DEFENSE_ARCHER_2_ADDITION_DEFENSE_ARCHER (RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_ARCHER_2_ADDITION_DEFENSE_ARCHER())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_RIDER_FOOD();
#define BUILDING_STOCK_UPGRADE_DEFENSE_RIDER_FOOD (RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_RIDER_FOOD())

int RuntimeConfig_TIME_BUILDING_STOCK_UPGRADE_DEFENSE_RIDER();
#define TIME_BUILDING_STOCK_UPGRADE_DEFENSE_RIDER (RuntimeConfig_TIME_BUILDING_STOCK_UPGRADE_DEFENSE_RIDER())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_RIDER_ADDITION_DEFENSE_RIDER();
#define BUILDING_STOCK_UPGRADE_DEFENSE_RIDER_ADDITION_DEFENSE_RIDER (RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_RIDER_ADDITION_DEFENSE_RIDER())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_RIDER_2_FOOD();
#define BUILDING_STOCK_UPGRADE_DEFENSE_RIDER_2_FOOD (RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_RIDER_2_FOOD())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_RIDER_2_GOLD();
#define BUILDING_STOCK_UPGRADE_DEFENSE_RIDER_2_GOLD (RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_RIDER_2_GOLD())

int RuntimeConfig_TIME_BUILDING_STOCK_UPGRADE_DEFENSE_RIDER_2();
#define TIME_BUILDING_STOCK_UPGRADE_DEFENSE_RIDER_2 (RuntimeConfig_TIME_BUILDING_STOCK_UPGRADE_DEFENSE_RIDER_2())

int RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_RIDER_2_ADDITION_DEFENSE_RIDER();
#define BUILDING_STOCK_UPGRADE_DEFENSE_RIDER_2_ADDITION_DEFENSE_RIDER (RuntimeConfig_BUILDING_STOCK_UPGRADE_DEFENSE_RIDER_2_ADDITION_DEFENSE_RIDER())

int RuntimeConfig_BUILDING_GRANARY_UPGRADE_ARROWTOWER_FOOD();
#define BUILDING_GRANARY_UPGRADE_ARROWTOWER_FOOD (RuntimeConfig_BUILDING_GRANARY_UPGRADE_ARROWTOWER_FOOD())

int RuntimeConfig_BUILDING_GRANARY_UPGRADE_ARROWTOWER_STONE();
#define BUILDING_GRANARY_UPGRADE_ARROWTOWER_STONE (RuntimeConfig_BUILDING_GRANARY_UPGRADE_ARROWTOWER_STONE())

int RuntimeConfig_TIME_BUILDING_GRANARY_UPGRADE_ARROWTOWER();
#define TIME_BUILDING_GRANARY_UPGRADE_ARROWTOWER (RuntimeConfig_TIME_BUILDING_GRANARY_UPGRADE_ARROWTOWER())

int RuntimeConfig_BUILDING_GRANARY_UPGRADE_ARROWTOWER_ADDITION_ATK();
#define BUILDING_GRANARY_UPGRADE_ARROWTOWER_ADDITION_ATK (RuntimeConfig_BUILDING_GRANARY_UPGRADE_ARROWTOWER_ADDITION_ATK())

int RuntimeConfig_BUILDING_GRANARY_UPGRADE_ARROWTOWER_ADDITION_DIS();
#define BUILDING_GRANARY_UPGRADE_ARROWTOWER_ADDITION_DIS (RuntimeConfig_BUILDING_GRANARY_UPGRADE_ARROWTOWER_ADDITION_DIS())

int RuntimeConfig_THROWMISSION_ARROWTOWER_UPGRADED();
#define THROWMISSION_ARROWTOWER_UPGRADED (RuntimeConfig_THROWMISSION_ARROWTOWER_UPGRADED())

int RuntimeConfig_BLOOD_BUILD_GRANARY();
#define BLOOD_BUILD_GRANARY (RuntimeConfig_BLOOD_BUILD_GRANARY())

int RuntimeConfig_VISION_GRANARY();
#define VISION_GRANARY (RuntimeConfig_VISION_GRANARY())

int RuntimeConfig_BUILD_GRANARY_WOOD();
#define BUILD_GRANARY_WOOD (RuntimeConfig_BUILD_GRANARY_WOOD())

int RuntimeConfig_TIME_BUILD_GRANARY();
#define TIME_BUILD_GRANARY (RuntimeConfig_TIME_BUILD_GRANARY())

int RuntimeConfig_BUILDING_GRANARY_ARROWTOWER_FOOD();
#define BUILDING_GRANARY_ARROWTOWER_FOOD (RuntimeConfig_BUILDING_GRANARY_ARROWTOWER_FOOD())

int RuntimeConfig_TIME_BUILDING_GRANARY_RESEARCH_ARROWTOWER();
#define TIME_BUILDING_GRANARY_RESEARCH_ARROWTOWER (RuntimeConfig_TIME_BUILDING_GRANARY_RESEARCH_ARROWTOWER())

int RuntimeConfig_BUILDING_GRANARY_RESEARCH_WALL_FOOD();
#define BUILDING_GRANARY_RESEARCH_WALL_FOOD (RuntimeConfig_BUILDING_GRANARY_RESEARCH_WALL_FOOD())

int RuntimeConfig_TIME_BUILDING_GRANARY_RESEARCH_WALL();
#define TIME_BUILDING_GRANARY_RESEARCH_WALL (RuntimeConfig_TIME_BUILDING_GRANARY_RESEARCH_WALL())

int RuntimeConfig_BLOOD_BUILD_ARMYCAMP();
#define BLOOD_BUILD_ARMYCAMP (RuntimeConfig_BLOOD_BUILD_ARMYCAMP())

int RuntimeConfig_VISION_ARMYCAMP();
#define VISION_ARMYCAMP (RuntimeConfig_VISION_ARMYCAMP())

int RuntimeConfig_BUILD_ARMYCAMP_WOOD();
#define BUILD_ARMYCAMP_WOOD (RuntimeConfig_BUILD_ARMYCAMP_WOOD())

int RuntimeConfig_TIME_BUILD_ARMYCAMP();
#define TIME_BUILD_ARMYCAMP (RuntimeConfig_TIME_BUILD_ARMYCAMP())

int RuntimeConfig_BUILDING_ARMYCAMP_CREATE_CLUBMAN_FOOD();
#define BUILDING_ARMYCAMP_CREATE_CLUBMAN_FOOD (RuntimeConfig_BUILDING_ARMYCAMP_CREATE_CLUBMAN_FOOD())

int RuntimeConfig_TIME_BUILDING_ARMYCAMP_CREATE_CLUBMAN();
#define TIME_BUILDING_ARMYCAMP_CREATE_CLUBMAN (RuntimeConfig_TIME_BUILDING_ARMYCAMP_CREATE_CLUBMAN())

int RuntimeConfig_BUILDING_ARMYCAMP_UPGRADE_CLUBMAN_FOOD();
#define BUILDING_ARMYCAMP_UPGRADE_CLUBMAN_FOOD (RuntimeConfig_BUILDING_ARMYCAMP_UPGRADE_CLUBMAN_FOOD())

int RuntimeConfig_TIME_BUILDING_ARMYCAMP_UPGRADE_CLUBMAN();
#define TIME_BUILDING_ARMYCAMP_UPGRADE_CLUBMAN (RuntimeConfig_TIME_BUILDING_ARMYCAMP_UPGRADE_CLUBMAN())

int RuntimeConfig_BUILDING_ARMYCAMP_CREATE_SLINGER_FOOD();
#define BUILDING_ARMYCAMP_CREATE_SLINGER_FOOD (RuntimeConfig_BUILDING_ARMYCAMP_CREATE_SLINGER_FOOD())

int RuntimeConfig_BUILDING_ARMYCAMP_CREATE_SLINGER_STONE();
#define BUILDING_ARMYCAMP_CREATE_SLINGER_STONE (RuntimeConfig_BUILDING_ARMYCAMP_CREATE_SLINGER_STONE())

int RuntimeConfig_TIME_BUILDING_ARMYCAMP_CREATE_SLINGER();
#define TIME_BUILDING_ARMYCAMP_CREATE_SLINGER (RuntimeConfig_TIME_BUILDING_ARMYCAMP_CREATE_SLINGER())

int RuntimeConfig_BUILDING_ARMYCAMP_CREATE_BROADSWORD_FOOD();
#define BUILDING_ARMYCAMP_CREATE_BROADSWORD_FOOD (RuntimeConfig_BUILDING_ARMYCAMP_CREATE_BROADSWORD_FOOD())

int RuntimeConfig_BUILDING_ARMYCAMP_CREATE_BROADSWORD_GOLD();
#define BUILDING_ARMYCAMP_CREATE_BROADSWORD_GOLD (RuntimeConfig_BUILDING_ARMYCAMP_CREATE_BROADSWORD_GOLD())

int RuntimeConfig_TIME_BUILDING_ARMYCAMP_CREATE_BROADSWORD();
#define TIME_BUILDING_ARMYCAMP_CREATE_BROADSWORD (RuntimeConfig_TIME_BUILDING_ARMYCAMP_CREATE_BROADSWORD())

int RuntimeConfig_BUILDING_ARMYCAMP_UPGRADE_BROADSWORD_FOOD();
#define BUILDING_ARMYCAMP_UPGRADE_BROADSWORD_FOOD (RuntimeConfig_BUILDING_ARMYCAMP_UPGRADE_BROADSWORD_FOOD())

int RuntimeConfig_BUILDING_ARMYCAMP_UPGRADE_BROADSWORD_GOLD();
#define BUILDING_ARMYCAMP_UPGRADE_BROADSWORD_GOLD (RuntimeConfig_BUILDING_ARMYCAMP_UPGRADE_BROADSWORD_GOLD())

int RuntimeConfig_TIME_BUILDING_ARMYCAMP_UPGRADE_BROADSWORD();
#define TIME_BUILDING_ARMYCAMP_UPGRADE_BROADSWORD (RuntimeConfig_TIME_BUILDING_ARMYCAMP_UPGRADE_BROADSWORD())

int RuntimeConfig_BUILDING_ARMYCAMP_RESEARCH_LOGISTICS_FOOD();
#define BUILDING_ARMYCAMP_RESEARCH_LOGISTICS_FOOD (RuntimeConfig_BUILDING_ARMYCAMP_RESEARCH_LOGISTICS_FOOD())

int RuntimeConfig_BUILDING_ARMYCAMP_RESEARCH_LOGISTICS_GOLD();
#define BUILDING_ARMYCAMP_RESEARCH_LOGISTICS_GOLD (RuntimeConfig_BUILDING_ARMYCAMP_RESEARCH_LOGISTICS_GOLD())

int RuntimeConfig_TIME_BUILDING_ARMYCAMP_RESEARCH_LOGISTICS();
#define TIME_BUILDING_ARMYCAMP_RESEARCH_LOGISTICS (RuntimeConfig_TIME_BUILDING_ARMYCAMP_RESEARCH_LOGISTICS())

int RuntimeConfig_BLOOD_BUILD_RANGE();
#define BLOOD_BUILD_RANGE (RuntimeConfig_BLOOD_BUILD_RANGE())

int RuntimeConfig_VISION_RANGE();
#define VISION_RANGE (RuntimeConfig_VISION_RANGE())

int RuntimeConfig_BUILD_RANGE_WOOD();
#define BUILD_RANGE_WOOD (RuntimeConfig_BUILD_RANGE_WOOD())

int RuntimeConfig_TIME_BUILD_RANGE();
#define TIME_BUILD_RANGE (RuntimeConfig_TIME_BUILD_RANGE())

int RuntimeConfig_BUILDING_RANGE_CREATE_BOWMAN_FOOD();
#define BUILDING_RANGE_CREATE_BOWMAN_FOOD (RuntimeConfig_BUILDING_RANGE_CREATE_BOWMAN_FOOD())

int RuntimeConfig_BUILDING_RANGE_CREATE_BOWMAN_WOOD();
#define BUILDING_RANGE_CREATE_BOWMAN_WOOD (RuntimeConfig_BUILDING_RANGE_CREATE_BOWMAN_WOOD())

int RuntimeConfig_TIME_BUILDING_RANGE_CREATE_BOWMAN();
#define TIME_BUILDING_RANGE_CREATE_BOWMAN (RuntimeConfig_TIME_BUILDING_RANGE_CREATE_BOWMAN())

int RuntimeConfig_BUILDING_RANGE_CREATE_COMPOSITE_BOWMAN_FOOD();
#define BUILDING_RANGE_CREATE_COMPOSITE_BOWMAN_FOOD (RuntimeConfig_BUILDING_RANGE_CREATE_COMPOSITE_BOWMAN_FOOD())

int RuntimeConfig_BUILDING_RANGE_CREATE_COMPOSITE_BOWMAN_GOLD();
#define BUILDING_RANGE_CREATE_COMPOSITE_BOWMAN_GOLD (RuntimeConfig_BUILDING_RANGE_CREATE_COMPOSITE_BOWMAN_GOLD())

int RuntimeConfig_TIME_BUILDING_RANGE_CREATE_COMPOSITE_BOWMAN();
#define TIME_BUILDING_RANGE_CREATE_COMPOSITE_BOWMAN (RuntimeConfig_TIME_BUILDING_RANGE_CREATE_COMPOSITE_BOWMAN())

int RuntimeConfig_BUILDING_RANGE_UPGRADE_COMPOSITE_BOW_FOOD();
#define BUILDING_RANGE_UPGRADE_COMPOSITE_BOW_FOOD (RuntimeConfig_BUILDING_RANGE_UPGRADE_COMPOSITE_BOW_FOOD())

int RuntimeConfig_BUILDING_RANGE_UPGRADE_COMPOSITE_BOW_WOOD();
#define BUILDING_RANGE_UPGRADE_COMPOSITE_BOW_WOOD (RuntimeConfig_BUILDING_RANGE_UPGRADE_COMPOSITE_BOW_WOOD())

int RuntimeConfig_TIME_BUILDING_RANGE_UPGRADE_COMPOSITE_BOW();
#define TIME_BUILDING_RANGE_UPGRADE_COMPOSITE_BOW (RuntimeConfig_TIME_BUILDING_RANGE_UPGRADE_COMPOSITE_BOW())

int RuntimeConfig_BLOOD_BUILD_STABLE();
#define BLOOD_BUILD_STABLE (RuntimeConfig_BLOOD_BUILD_STABLE())

int RuntimeConfig_VISION_STABLE();
#define VISION_STABLE (RuntimeConfig_VISION_STABLE())

int RuntimeConfig_BUILD_STABLE_WOOD();
#define BUILD_STABLE_WOOD (RuntimeConfig_BUILD_STABLE_WOOD())

int RuntimeConfig_TIME_BUILD_STABLE();
#define TIME_BUILD_STABLE (RuntimeConfig_TIME_BUILD_STABLE())

int RuntimeConfig_BUILDING_RANGE_CREATE_CHARIOT_ARCHER_FOOD();
#define BUILDING_RANGE_CREATE_CHARIOT_ARCHER_FOOD (RuntimeConfig_BUILDING_RANGE_CREATE_CHARIOT_ARCHER_FOOD())

int RuntimeConfig_BUILDING_RANGE_CREATE_CHARIOT_ARCHER_WOOD();
#define BUILDING_RANGE_CREATE_CHARIOT_ARCHER_WOOD (RuntimeConfig_BUILDING_RANGE_CREATE_CHARIOT_ARCHER_WOOD())

int RuntimeConfig_TIME_BUILDING_RANGE_CREATE_CHARIOT_ARCHER();
#define TIME_BUILDING_RANGE_CREATE_CHARIOT_ARCHER (RuntimeConfig_TIME_BUILDING_RANGE_CREATE_CHARIOT_ARCHER())

int RuntimeConfig_BUILDING_STABLE_CREATE_SCOUT_FOOD();
#define BUILDING_STABLE_CREATE_SCOUT_FOOD (RuntimeConfig_BUILDING_STABLE_CREATE_SCOUT_FOOD())

int RuntimeConfig_TIME_BUILDING_STABLE_CREATE_SCOUT();
#define TIME_BUILDING_STABLE_CREATE_SCOUT (RuntimeConfig_TIME_BUILDING_STABLE_CREATE_SCOUT())

int RuntimeConfig_BUILDING_STABLE_CREATE_CAVALRY_FOOD();
#define BUILDING_STABLE_CREATE_CAVALRY_FOOD (RuntimeConfig_BUILDING_STABLE_CREATE_CAVALRY_FOOD())

int RuntimeConfig_BUILDING_STABLE_CREATE_CAVALRY_GOLD();
#define BUILDING_STABLE_CREATE_CAVALRY_GOLD (RuntimeConfig_BUILDING_STABLE_CREATE_CAVALRY_GOLD())

int RuntimeConfig_TIME_BUILDING_STABLE_CREATE_CAVALRY();
#define TIME_BUILDING_STABLE_CREATE_CAVALRY (RuntimeConfig_TIME_BUILDING_STABLE_CREATE_CAVALRY())

int RuntimeConfig_BUILDING_STABLE_CREATE_CHARIOT_FOOD();
#define BUILDING_STABLE_CREATE_CHARIOT_FOOD (RuntimeConfig_BUILDING_STABLE_CREATE_CHARIOT_FOOD())

int RuntimeConfig_BUILDING_STABLE_CREATE_CHARIOT_WOOD();
#define BUILDING_STABLE_CREATE_CHARIOT_WOOD (RuntimeConfig_BUILDING_STABLE_CREATE_CHARIOT_WOOD())

int RuntimeConfig_TIME_BUILDING_STABLE_CREATE_CHARIOT();
#define TIME_BUILDING_STABLE_CREATE_CHARIOT (RuntimeConfig_TIME_BUILDING_STABLE_CREATE_CHARIOT())

int RuntimeConfig_BLOOD_BUILD_MARKET();
#define BLOOD_BUILD_MARKET (RuntimeConfig_BLOOD_BUILD_MARKET())

int RuntimeConfig_VISION_MARKET();
#define VISION_MARKET (RuntimeConfig_VISION_MARKET())

int RuntimeConfig_BUILD_MARKET_WOOD();
#define BUILD_MARKET_WOOD (RuntimeConfig_BUILD_MARKET_WOOD())

int RuntimeConfig_TIME_BUILD_MARKET();
#define TIME_BUILD_MARKET (RuntimeConfig_TIME_BUILD_MARKET())

int RuntimeConfig_BLOOD_BUILD_DOCK();
#define BLOOD_BUILD_DOCK (RuntimeConfig_BLOOD_BUILD_DOCK())

int RuntimeConfig_VISION_DOCK();
#define VISION_DOCK (RuntimeConfig_VISION_DOCK())

int RuntimeConfig_BUILD_DOCK_WOOD();
#define BUILD_DOCK_WOOD (RuntimeConfig_BUILD_DOCK_WOOD())

int RuntimeConfig_TIME_BUILD_DOCK();
#define TIME_BUILD_DOCK (RuntimeConfig_TIME_BUILD_DOCK())

int RuntimeConfig_BUILDING_DOCK_CREATE_SHIP_WOOD();
#define BUILDING_DOCK_CREATE_SHIP_WOOD (RuntimeConfig_BUILDING_DOCK_CREATE_SHIP_WOOD())

int RuntimeConfig_TIME_BUILDING_DOCK_CREATE_SHIP();
#define TIME_BUILDING_DOCK_CREATE_SHIP (RuntimeConfig_TIME_BUILDING_DOCK_CREATE_SHIP())

int RuntimeConfig_BUILDING_DOCK_CREATE_SAILING_WOOD();
#define BUILDING_DOCK_CREATE_SAILING_WOOD (RuntimeConfig_BUILDING_DOCK_CREATE_SAILING_WOOD())

int RuntimeConfig_TIME_BUILDING_DOCK_CREATE_SAILING();
#define TIME_BUILDING_DOCK_CREATE_SAILING (RuntimeConfig_TIME_BUILDING_DOCK_CREATE_SAILING())

int RuntimeConfig_BUILDING_DOCK_CREATE_WOOD_BOAT_WOOD();
#define BUILDING_DOCK_CREATE_WOOD_BOAT_WOOD (RuntimeConfig_BUILDING_DOCK_CREATE_WOOD_BOAT_WOOD())

int RuntimeConfig_TIME_BUILDING_DOCK_CREATE_WOOD_BOAT();
#define TIME_BUILDING_DOCK_CREATE_WOOD_BOAT (RuntimeConfig_TIME_BUILDING_DOCK_CREATE_WOOD_BOAT())

int RuntimeConfig_BUILDING_MARKET_WOOD_UPGRADE_FOOD();
#define BUILDING_MARKET_WOOD_UPGRADE_FOOD (RuntimeConfig_BUILDING_MARKET_WOOD_UPGRADE_FOOD())

int RuntimeConfig_BUILDING_MARKET_WOOD_UPGRADE_WOOD();
#define BUILDING_MARKET_WOOD_UPGRADE_WOOD (RuntimeConfig_BUILDING_MARKET_WOOD_UPGRADE_WOOD())

int RuntimeConfig_TIME_BUILDING_MARKET_UPGRADE_CUTTING();
#define TIME_BUILDING_MARKET_UPGRADE_CUTTING (RuntimeConfig_TIME_BUILDING_MARKET_UPGRADE_CUTTING())

int RuntimeConfig_BUILDING_MARKET_WOOD_UPGRADE_ADDITION_CARRY();
#define BUILDING_MARKET_WOOD_UPGRADE_ADDITION_CARRY (RuntimeConfig_BUILDING_MARKET_WOOD_UPGRADE_ADDITION_CARRY())

int RuntimeConfig_BUILDING_MARKET_WOOD_UPGRADE_ADDITION_GATHERRATE();
#define BUILDING_MARKET_WOOD_UPGRADE_ADDITION_GATHERRATE (RuntimeConfig_BUILDING_MARKET_WOOD_UPGRADE_ADDITION_GATHERRATE())

int RuntimeConfig_BUILDING_MARKET_WOOD_UPGRADE_ADDITION_DISSHOOT();
#define BUILDING_MARKET_WOOD_UPGRADE_ADDITION_DISSHOOT (RuntimeConfig_BUILDING_MARKET_WOOD_UPGRADE_ADDITION_DISSHOOT())

int RuntimeConfig_BLOOD_BUILD_SIEGE();
#define BLOOD_BUILD_SIEGE (RuntimeConfig_BLOOD_BUILD_SIEGE())

int RuntimeConfig_VISION_SIEGE();
#define VISION_SIEGE (RuntimeConfig_VISION_SIEGE())

int RuntimeConfig_BUILD_SIEGE_WOOD();
#define BUILD_SIEGE_WOOD (RuntimeConfig_BUILD_SIEGE_WOOD())

int RuntimeConfig_TIME_BUILD_SIEGE();
#define TIME_BUILD_SIEGE (RuntimeConfig_TIME_BUILD_SIEGE())

int RuntimeConfig_BLOOD_BUILD_COLLAGE();
#define BLOOD_BUILD_COLLAGE (RuntimeConfig_BLOOD_BUILD_COLLAGE())

int RuntimeConfig_VISION_COLLAGE();
#define VISION_COLLAGE (RuntimeConfig_VISION_COLLAGE())

int RuntimeConfig_BUILD_COLLAGE_WOOD();
#define BUILD_COLLAGE_WOOD (RuntimeConfig_BUILD_COLLAGE_WOOD())

int RuntimeConfig_TIME_BUILD_COLLAGE();
#define TIME_BUILD_COLLAGE (RuntimeConfig_TIME_BUILD_COLLAGE())

int RuntimeConfig_BUILDING_COLLAGE_CREATE_HOPLITE_FOOD();
#define BUILDING_COLLAGE_CREATE_HOPLITE_FOOD (RuntimeConfig_BUILDING_COLLAGE_CREATE_HOPLITE_FOOD())

int RuntimeConfig_BUILDING_COLLAGE_CREATE_HOPLITE_GOLD();
#define BUILDING_COLLAGE_CREATE_HOPLITE_GOLD (RuntimeConfig_BUILDING_COLLAGE_CREATE_HOPLITE_GOLD())

int RuntimeConfig_TIME_BUILDING_COLLAGE_CREATE_HOPLITE();
#define TIME_BUILDING_COLLAGE_CREATE_HOPLITE (RuntimeConfig_TIME_BUILDING_COLLAGE_CREATE_HOPLITE())

int RuntimeConfig_BUILDING_SIEGE_CREATE_STONE_THROWER_WOOD();
#define BUILDING_SIEGE_CREATE_STONE_THROWER_WOOD (RuntimeConfig_BUILDING_SIEGE_CREATE_STONE_THROWER_WOOD())

int RuntimeConfig_BUILDING_SIEGE_CREATE_STONE_THROWER_GOLD();
#define BUILDING_SIEGE_CREATE_STONE_THROWER_GOLD (RuntimeConfig_BUILDING_SIEGE_CREATE_STONE_THROWER_GOLD())

int RuntimeConfig_TIME_BUILDING_SIEGE_CREATE_STONE_THROWER();
#define TIME_BUILDING_SIEGE_CREATE_STONE_THROWER (RuntimeConfig_TIME_BUILDING_SIEGE_CREATE_STONE_THROWER())

int RuntimeConfig_BUILDING_MARKET_STONE_UPGRADE_FOOD();
#define BUILDING_MARKET_STONE_UPGRADE_FOOD (RuntimeConfig_BUILDING_MARKET_STONE_UPGRADE_FOOD())

int RuntimeConfig_BUILDING_MARKET_STONE_UPGRADE_STONE();
#define BUILDING_MARKET_STONE_UPGRADE_STONE (RuntimeConfig_BUILDING_MARKET_STONE_UPGRADE_STONE())

int RuntimeConfig_TIME_BUILDING_MARKET_UPGRADE_DIGGINGSOTNE();
#define TIME_BUILDING_MARKET_UPGRADE_DIGGINGSOTNE (RuntimeConfig_TIME_BUILDING_MARKET_UPGRADE_DIGGINGSOTNE())

int RuntimeConfig_BUILDING_MARKET_STONE_UPGRADE_ADDITION_CARRY();
#define BUILDING_MARKET_STONE_UPGRADE_ADDITION_CARRY (RuntimeConfig_BUILDING_MARKET_STONE_UPGRADE_ADDITION_CARRY())

int RuntimeConfig_BUILDING_MARKET_STONE_UPGRADE_ADDITION_GATHERRATE();
#define BUILDING_MARKET_STONE_UPGRADE_ADDITION_GATHERRATE (RuntimeConfig_BUILDING_MARKET_STONE_UPGRADE_ADDITION_GATHERRATE())

int RuntimeConfig_BUILDING_MARKET_STONE_UPGRADE_ADDITION_SILNGERATK();
#define BUILDING_MARKET_STONE_UPGRADE_ADDITION_SILNGERATK (RuntimeConfig_BUILDING_MARKET_STONE_UPGRADE_ADDITION_SILNGERATK())

int RuntimeConfig_BUILDING_MARKET_STONE_UPGRADE_ADDITION_SILNGERDIS();
#define BUILDING_MARKET_STONE_UPGRADE_ADDITION_SILNGERDIS (RuntimeConfig_BUILDING_MARKET_STONE_UPGRADE_ADDITION_SILNGERDIS())

int RuntimeConfig_BUILDING_MARKET_GOLD_UPGRADE_FOOD();
#define BUILDING_MARKET_GOLD_UPGRADE_FOOD (RuntimeConfig_BUILDING_MARKET_GOLD_UPGRADE_FOOD())

int RuntimeConfig_BUILDING_MARKET_GOLD_UPGRADE_WOOD();
#define BUILDING_MARKET_GOLD_UPGRADE_WOOD (RuntimeConfig_BUILDING_MARKET_GOLD_UPGRADE_WOOD())

int RuntimeConfig_TIME_BUILDING_MARKET_UPGRADE_GOLD();
#define TIME_BUILDING_MARKET_UPGRADE_GOLD (RuntimeConfig_TIME_BUILDING_MARKET_UPGRADE_GOLD())

int RuntimeConfig_BUILDING_MARKET_GOLD_UPGRADE_ADDITION_CARRY();
#define BUILDING_MARKET_GOLD_UPGRADE_ADDITION_CARRY (RuntimeConfig_BUILDING_MARKET_GOLD_UPGRADE_ADDITION_CARRY())

int RuntimeConfig_BUILDING_MARKET_GOLD_UPGRADE_ADDITION_GATHERRATE();
#define BUILDING_MARKET_GOLD_UPGRADE_ADDITION_GATHERRATE (RuntimeConfig_BUILDING_MARKET_GOLD_UPGRADE_ADDITION_GATHERRATE())

int RuntimeConfig_BUILDING_MARKET_FARM_UPGRADE_FOOD();
#define BUILDING_MARKET_FARM_UPGRADE_FOOD (RuntimeConfig_BUILDING_MARKET_FARM_UPGRADE_FOOD())

int RuntimeConfig_BUILDING_MARKET_FARM_UPGRADE_WOOD();
#define BUILDING_MARKET_FARM_UPGRADE_WOOD (RuntimeConfig_BUILDING_MARKET_FARM_UPGRADE_WOOD())

int RuntimeConfig_TIME_BUILDING_MARKET_UPGRADE_FARM();
#define TIME_BUILDING_MARKET_UPGRADE_FARM (RuntimeConfig_TIME_BUILDING_MARKET_UPGRADE_FARM())

int RuntimeConfig_BUILDING_MARKET_FARM_UPGRADE_ADDITION_FOOD();
#define BUILDING_MARKET_FARM_UPGRADE_ADDITION_FOOD (RuntimeConfig_BUILDING_MARKET_FARM_UPGRADE_ADDITION_FOOD())

int RuntimeConfig_BUILDING_MARKET_WHEEL_UPGRADE_FOOD();
#define BUILDING_MARKET_WHEEL_UPGRADE_FOOD (RuntimeConfig_BUILDING_MARKET_WHEEL_UPGRADE_FOOD())

int RuntimeConfig_BUILDING_MARKET_WHEEL_UPGRADE_WOOD();
#define BUILDING_MARKET_WHEEL_UPGRADE_WOOD (RuntimeConfig_BUILDING_MARKET_WHEEL_UPGRADE_WOOD())

int RuntimeConfig_TIME_BUILDING_MARKET_WHEEL_UPGRADE();
#define TIME_BUILDING_MARKET_WHEEL_UPGRADE (RuntimeConfig_TIME_BUILDING_MARKET_WHEEL_UPGRADE())

int RuntimeConfig_BUILDING_MARKET_CRAFT_UPGRADE_FOOD();
#define BUILDING_MARKET_CRAFT_UPGRADE_FOOD (RuntimeConfig_BUILDING_MARKET_CRAFT_UPGRADE_FOOD())

int RuntimeConfig_BUILDING_MARKET_CRAFT_UPGRADE_WOOD();
#define BUILDING_MARKET_CRAFT_UPGRADE_WOOD (RuntimeConfig_BUILDING_MARKET_CRAFT_UPGRADE_WOOD())

int RuntimeConfig_TIME_BUILDING_MARKET_CRAFT_UPGRADE();
#define TIME_BUILDING_MARKET_CRAFT_UPGRADE (RuntimeConfig_TIME_BUILDING_MARKET_CRAFT_UPGRADE())

int RuntimeConfig_BUILDING_MARKET_CRAFT_UPGRADE_ADDITION_DISSHOOT();
#define BUILDING_MARKET_CRAFT_UPGRADE_ADDITION_DISSHOOT (RuntimeConfig_BUILDING_MARKET_CRAFT_UPGRADE_ADDITION_DISSHOOT())

int RuntimeConfig_BUILDING_MARKET_CRAFT_UPGRADE_ADDITION_GATHERRATE();
#define BUILDING_MARKET_CRAFT_UPGRADE_ADDITION_GATHERRATE (RuntimeConfig_BUILDING_MARKET_CRAFT_UPGRADE_ADDITION_GATHERRATE())

int RuntimeConfig_BUILDING_MARKET_PLOW_UPGRADE_FOOD();
#define BUILDING_MARKET_PLOW_UPGRADE_FOOD (RuntimeConfig_BUILDING_MARKET_PLOW_UPGRADE_FOOD())

int RuntimeConfig_BUILDING_MARKET_PLOW_UPGRADE_WOOD();
#define BUILDING_MARKET_PLOW_UPGRADE_WOOD (RuntimeConfig_BUILDING_MARKET_PLOW_UPGRADE_WOOD())

int RuntimeConfig_TIME_BUILDING_MARKET_PLOW_UPGRADE();
#define TIME_BUILDING_MARKET_PLOW_UPGRADE (RuntimeConfig_TIME_BUILDING_MARKET_PLOW_UPGRADE())

int RuntimeConfig_BUILDING_MARKET_PLOW_UPGRADE_ADDITION_FOOD();
#define BUILDING_MARKET_PLOW_UPGRADE_ADDITION_FOOD (RuntimeConfig_BUILDING_MARKET_PLOW_UPGRADE_ADDITION_FOOD())

int RuntimeConfig_BLOOD_BUILD_FARM();
#define BLOOD_BUILD_FARM (RuntimeConfig_BLOOD_BUILD_FARM())

int RuntimeConfig_CNT_BUILD_FARM();
#define CNT_BUILD_FARM (RuntimeConfig_CNT_BUILD_FARM())

int RuntimeConfig_VISION_FARM();
#define VISION_FARM (RuntimeConfig_VISION_FARM())

int RuntimeConfig_BUILD_FARM_WOOD();
#define BUILD_FARM_WOOD (RuntimeConfig_BUILD_FARM_WOOD())

int RuntimeConfig_TIME_BUILD_FARM();
#define TIME_BUILD_FARM (RuntimeConfig_TIME_BUILD_FARM())

int RuntimeConfig_BLOOD_BUILD_ARROWTOWER();
#define BLOOD_BUILD_ARROWTOWER (RuntimeConfig_BLOOD_BUILD_ARROWTOWER())

Double RuntimeConfig_VISION_ARROWTOWER();
#define VISION_ARROWTOWER (RuntimeConfig_VISION_ARROWTOWER())

int RuntimeConfig_DIS_BUILD_ARROWTOWER();
#define DIS_BUILD_ARROWTOWER (RuntimeConfig_DIS_BUILD_ARROWTOWER())

int RuntimeConfig_ATK_BUILD_ARROWTOWER();
#define ATK_BUILD_ARROWTOWER (RuntimeConfig_ATK_BUILD_ARROWTOWER())

int RuntimeConfig_DEFSHOOT_BUILD_ARROWTOWER();
#define DEFSHOOT_BUILD_ARROWTOWER (RuntimeConfig_DEFSHOOT_BUILD_ARROWTOWER())

int RuntimeConfig_BUILD_ARROWTOWER_STONE();
#define BUILD_ARROWTOWER_STONE (RuntimeConfig_BUILD_ARROWTOWER_STONE())

int RuntimeConfig_TIME_BUILD_ARROWTOWER();
#define TIME_BUILD_ARROWTOWER (RuntimeConfig_TIME_BUILD_ARROWTOWER())

int RuntimeConfig_BLOOD_BUILD_WALL();
#define BLOOD_BUILD_WALL (RuntimeConfig_BLOOD_BUILD_WALL())

int RuntimeConfig_DEFSHOOT_BUILD_WALL();
#define DEFSHOOT_BUILD_WALL (RuntimeConfig_DEFSHOOT_BUILD_WALL())

int RuntimeConfig_BUILD_WALL_STONE();
#define BUILD_WALL_STONE (RuntimeConfig_BUILD_WALL_STONE())

int RuntimeConfig_TIME_BUILD_WALL();
#define TIME_BUILD_WALL (RuntimeConfig_TIME_BUILD_WALL())

Double RuntimeConfig_DISTANCE_Manhattan_MoveEndNEAR();
#define DISTANCE_Manhattan_MoveEndNEAR (RuntimeConfig_DISTANCE_Manhattan_MoveEndNEAR())

Double RuntimeConfig_DISTANCE_Manhattan_PathMove();
#define DISTANCE_Manhattan_PathMove (RuntimeConfig_DISTANCE_Manhattan_PathMove())

Double RuntimeConfig_DISTANCE_Manhattan_Unload();
#define DISTANCE_Manhattan_Unload (RuntimeConfig_DISTANCE_Manhattan_Unload())

Double RuntimeConfig_DISTANCE_Manhattan_Transport();
#define DISTANCE_Manhattan_Transport (RuntimeConfig_DISTANCE_Manhattan_Transport())

Double RuntimeConfig_DISTANCE_ATTACK_CLOSE();
#define DISTANCE_ATTACK_CLOSE (RuntimeConfig_DISTANCE_ATTACK_CLOSE())

Double RuntimeConfig_DISTANCE_HIT_TARGET();
#define DISTANCE_HIT_TARGET (RuntimeConfig_DISTANCE_HIT_TARGET())

Double RuntimeConfig_DISTANCE_ELEPHANT_ATTACK();
#define DISTANCE_ELEPHANT_ATTACK (RuntimeConfig_DISTANCE_ELEPHANT_ATTACK())

Double RuntimeConfig_SHIP_ACT_MAX_DISTANCE();
#define SHIP_ACT_MAX_DISTANCE (RuntimeConfig_SHIP_ACT_MAX_DISTANCE())

Double RuntimeConfig_DIS_ARROWTOWER();
#define DIS_ARROWTOWER (RuntimeConfig_DIS_ARROWTOWER())

Double RuntimeConfig_SPEED_CLUBMAN1();
#define SPEED_CLUBMAN1 (RuntimeConfig_SPEED_CLUBMAN1())

int RuntimeConfig_VISION_CLUBMAN1();
#define VISION_CLUBMAN1 (RuntimeConfig_VISION_CLUBMAN1())

int RuntimeConfig_DIS_CLUBMAN1();
#define DIS_CLUBMAN1 (RuntimeConfig_DIS_CLUBMAN1())

Double RuntimeConfig_INTERVAL_CLUBMAN1();
#define INTERVAL_CLUBMAN1 (RuntimeConfig_INTERVAL_CLUBMAN1())

int RuntimeConfig_ATK_CLUBMAN1();
#define ATK_CLUBMAN1 (RuntimeConfig_ATK_CLUBMAN1())

int RuntimeConfig_DEFCLOSE_CLUBMAN1();
#define DEFCLOSE_CLUBMAN1 (RuntimeConfig_DEFCLOSE_CLUBMAN1())

int RuntimeConfig_DEFSHOOT_CLUBMAN1();
#define DEFSHOOT_CLUBMAN1 (RuntimeConfig_DEFSHOOT_CLUBMAN1())

int RuntimeConfig_BLOOD_CLUBMAN1();
#define BLOOD_CLUBMAN1 (RuntimeConfig_BLOOD_CLUBMAN1())

int RuntimeConfig_BLOOD_CLUBMAN2();
#define BLOOD_CLUBMAN2 (RuntimeConfig_BLOOD_CLUBMAN2())

Double RuntimeConfig_SPEED_CLUBMAN2();
#define SPEED_CLUBMAN2 (RuntimeConfig_SPEED_CLUBMAN2())

int RuntimeConfig_VISION_CLUBMAN2();
#define VISION_CLUBMAN2 (RuntimeConfig_VISION_CLUBMAN2())

int RuntimeConfig_DIS_CLUBMAN2();
#define DIS_CLUBMAN2 (RuntimeConfig_DIS_CLUBMAN2())

Double RuntimeConfig_INTERVAL_CLUBMAN2();
#define INTERVAL_CLUBMAN2 (RuntimeConfig_INTERVAL_CLUBMAN2())

int RuntimeConfig_ATK_CLUBMAN2();
#define ATK_CLUBMAN2 (RuntimeConfig_ATK_CLUBMAN2())

int RuntimeConfig_DEFCLOSE_CLUBMAN2();
#define DEFCLOSE_CLUBMAN2 (RuntimeConfig_DEFCLOSE_CLUBMAN2())

int RuntimeConfig_DEFSHOOT_CLUBMAN2();
#define DEFSHOOT_CLUBMAN2 (RuntimeConfig_DEFSHOOT_CLUBMAN2())

int RuntimeConfig_BLOOD_SHORTSWORDSMAN1();
#define BLOOD_SHORTSWORDSMAN1 (RuntimeConfig_BLOOD_SHORTSWORDSMAN1())

Double RuntimeConfig_SPEED_SHORTSWORDSMAN1();
#define SPEED_SHORTSWORDSMAN1 (RuntimeConfig_SPEED_SHORTSWORDSMAN1())

int RuntimeConfig_VISION_SHORTSWORDSMAN1();
#define VISION_SHORTSWORDSMAN1 (RuntimeConfig_VISION_SHORTSWORDSMAN1())

int RuntimeConfig_DIS_SHORTSWORDSMAN1();
#define DIS_SHORTSWORDSMAN1 (RuntimeConfig_DIS_SHORTSWORDSMAN1())

Double RuntimeConfig_INTERVAL_SHORTSWORDSMAN1();
#define INTERVAL_SHORTSWORDSMAN1 (RuntimeConfig_INTERVAL_SHORTSWORDSMAN1())

int RuntimeConfig_ATK_SHORTSWORSMAN1();
#define ATK_SHORTSWORSMAN1 (RuntimeConfig_ATK_SHORTSWORSMAN1())

int RuntimeConfig_DEFCLOSE_SHORTSWORSMAN1();
#define DEFCLOSE_SHORTSWORSMAN1 (RuntimeConfig_DEFCLOSE_SHORTSWORSMAN1())

int RuntimeConfig_DEFSHOOT_SHORTSWORSMAN1();
#define DEFSHOOT_SHORTSWORSMAN1 (RuntimeConfig_DEFSHOOT_SHORTSWORSMAN1())

int RuntimeConfig_BLOOD_SHORTSWORDSMAN2();
#define BLOOD_SHORTSWORDSMAN2 (RuntimeConfig_BLOOD_SHORTSWORDSMAN2())

Double RuntimeConfig_SPEED_SHORTSWORDSMAN2();
#define SPEED_SHORTSWORDSMAN2 (RuntimeConfig_SPEED_SHORTSWORDSMAN2())

int RuntimeConfig_VISION_SHORTSWORDSMAN2();
#define VISION_SHORTSWORDSMAN2 (RuntimeConfig_VISION_SHORTSWORDSMAN2())

int RuntimeConfig_DIS_SHORTSWORDSMAN2();
#define DIS_SHORTSWORDSMAN2 (RuntimeConfig_DIS_SHORTSWORDSMAN2())

Double RuntimeConfig_INTERVAL_SHORTSWORDSMAN2();
#define INTERVAL_SHORTSWORDSMAN2 (RuntimeConfig_INTERVAL_SHORTSWORDSMAN2())

int RuntimeConfig_ATK_SHORTSWORSMAN2();
#define ATK_SHORTSWORSMAN2 (RuntimeConfig_ATK_SHORTSWORSMAN2())

int RuntimeConfig_DEFCLOSE_SHORTSWORSMAN2();
#define DEFCLOSE_SHORTSWORSMAN2 (RuntimeConfig_DEFCLOSE_SHORTSWORSMAN2())

int RuntimeConfig_DEFSHOOT_SHORTSWORSMAN2();
#define DEFSHOOT_SHORTSWORSMAN2 (RuntimeConfig_DEFSHOOT_SHORTSWORSMAN2())

int RuntimeConfig_BLOOD_SHORTSWORDSMAN3();
#define BLOOD_SHORTSWORDSMAN3 (RuntimeConfig_BLOOD_SHORTSWORDSMAN3())

Double RuntimeConfig_SPEED_SHORTSWORDSMAN3();
#define SPEED_SHORTSWORDSMAN3 (RuntimeConfig_SPEED_SHORTSWORDSMAN3())

int RuntimeConfig_VISION_SHORTSWORDSMAN3();
#define VISION_SHORTSWORDSMAN3 (RuntimeConfig_VISION_SHORTSWORDSMAN3())

int RuntimeConfig_DIS_SHORTSWORDSMAN3();
#define DIS_SHORTSWORDSMAN3 (RuntimeConfig_DIS_SHORTSWORDSMAN3())

Double RuntimeConfig_INTERVAL_SHORTSWORDSMAN3();
#define INTERVAL_SHORTSWORDSMAN3 (RuntimeConfig_INTERVAL_SHORTSWORDSMAN3())

int RuntimeConfig_ATK_SHORTSWORSMAN3();
#define ATK_SHORTSWORSMAN3 (RuntimeConfig_ATK_SHORTSWORSMAN3())

int RuntimeConfig_DEFCLOSE_SHORTSWORSMAN3();
#define DEFCLOSE_SHORTSWORSMAN3 (RuntimeConfig_DEFCLOSE_SHORTSWORSMAN3())

int RuntimeConfig_DEFSHOOT_SHORTSWORSMAN3();
#define DEFSHOOT_SHORTSWORSMAN3 (RuntimeConfig_DEFSHOOT_SHORTSWORSMAN3())

int RuntimeConfig_BLOOD_SHORTSWORDSMAN4();
#define BLOOD_SHORTSWORDSMAN4 (RuntimeConfig_BLOOD_SHORTSWORDSMAN4())

Double RuntimeConfig_SPEED_SHORTSWORDSMAN4();
#define SPEED_SHORTSWORDSMAN4 (RuntimeConfig_SPEED_SHORTSWORDSMAN4())

int RuntimeConfig_VISION_SHORTSWORDSMAN4();
#define VISION_SHORTSWORDSMAN4 (RuntimeConfig_VISION_SHORTSWORDSMAN4())

int RuntimeConfig_DIS_SHORTSWORDSMAN4();
#define DIS_SHORTSWORDSMAN4 (RuntimeConfig_DIS_SHORTSWORDSMAN4())

Double RuntimeConfig_INTERVAL_SHORTSWORDSMAN4();
#define INTERVAL_SHORTSWORDSMAN4 (RuntimeConfig_INTERVAL_SHORTSWORDSMAN4())

int RuntimeConfig_ATK_SHORTSWORSMAN4();
#define ATK_SHORTSWORSMAN4 (RuntimeConfig_ATK_SHORTSWORSMAN4())

int RuntimeConfig_DEFCLOSE_SHORTSWORSMAN4();
#define DEFCLOSE_SHORTSWORSMAN4 (RuntimeConfig_DEFCLOSE_SHORTSWORSMAN4())

int RuntimeConfig_DEFSHOOT_SHORTSWORSMAN4();
#define DEFSHOOT_SHORTSWORSMAN4 (RuntimeConfig_DEFSHOOT_SHORTSWORSMAN4())

int RuntimeConfig_BLOOD_BROADSWORDSMAN();
#define BLOOD_BROADSWORDSMAN (RuntimeConfig_BLOOD_BROADSWORDSMAN())

Double RuntimeConfig_SPEED_BROADSWORDSMAN();
#define SPEED_BROADSWORDSMAN (RuntimeConfig_SPEED_BROADSWORDSMAN())

int RuntimeConfig_VISION_BROADSWORDSMAN();
#define VISION_BROADSWORDSMAN (RuntimeConfig_VISION_BROADSWORDSMAN())

int RuntimeConfig_ATK_BROADSWORDSMAN();
#define ATK_BROADSWORDSMAN (RuntimeConfig_ATK_BROADSWORDSMAN())

Double RuntimeConfig_DIS_BROADSWORDSMAN();
#define DIS_BROADSWORDSMAN (RuntimeConfig_DIS_BROADSWORDSMAN())

Double RuntimeConfig_INTERVAL_BROADSWORDSMAN();
#define INTERVAL_BROADSWORDSMAN (RuntimeConfig_INTERVAL_BROADSWORDSMAN())

int RuntimeConfig_DEFCLOSE_BROADSWORDSMAN();
#define DEFCLOSE_BROADSWORDSMAN (RuntimeConfig_DEFCLOSE_BROADSWORDSMAN())

int RuntimeConfig_DEFSHOOT_BROADSWORDSMAN();
#define DEFSHOOT_BROADSWORDSMAN (RuntimeConfig_DEFSHOOT_BROADSWORDSMAN())

int RuntimeConfig_NOWRES_TIMER_BROADSWORDSMAN();
#define NOWRES_TIMER_BROADSWORDSMAN (RuntimeConfig_NOWRES_TIMER_BROADSWORDSMAN())

int RuntimeConfig_BLOOD_SLINGER();
#define BLOOD_SLINGER (RuntimeConfig_BLOOD_SLINGER())

Double RuntimeConfig_SPEED_SLINGER();
#define SPEED_SLINGER (RuntimeConfig_SPEED_SLINGER())

int RuntimeConfig_VISION_SLINGER();
#define VISION_SLINGER (RuntimeConfig_VISION_SLINGER())

int RuntimeConfig_DIS_SLINGER();
#define DIS_SLINGER (RuntimeConfig_DIS_SLINGER())

Double RuntimeConfig_INTERVAL_SLINGER();
#define INTERVAL_SLINGER (RuntimeConfig_INTERVAL_SLINGER())

int RuntimeConfig_ATK_SLINGER();
#define ATK_SLINGER (RuntimeConfig_ATK_SLINGER())

int RuntimeConfig_DEFCLOSE_SLINGER();
#define DEFCLOSE_SLINGER (RuntimeConfig_DEFCLOSE_SLINGER())

int RuntimeConfig_DEFSHOOT_SLINGER();
#define DEFSHOOT_SLINGER (RuntimeConfig_DEFSHOOT_SLINGER())

int RuntimeConfig_BLOOD_BOWMAN();
#define BLOOD_BOWMAN (RuntimeConfig_BLOOD_BOWMAN())

Double RuntimeConfig_SPEED_BOWMAN();
#define SPEED_BOWMAN (RuntimeConfig_SPEED_BOWMAN())

int RuntimeConfig_VISION_BOWMAN();
#define VISION_BOWMAN (RuntimeConfig_VISION_BOWMAN())

int RuntimeConfig_DIS_BOWMAN();
#define DIS_BOWMAN (RuntimeConfig_DIS_BOWMAN())

Double RuntimeConfig_INTERVAL_BOWMAN();
#define INTERVAL_BOWMAN (RuntimeConfig_INTERVAL_BOWMAN())

int RuntimeConfig_ATK_BOWMAN();
#define ATK_BOWMAN (RuntimeConfig_ATK_BOWMAN())

int RuntimeConfig_DEFCLOSE_BOWMAN();
#define DEFCLOSE_BOWMAN (RuntimeConfig_DEFCLOSE_BOWMAN())

int RuntimeConfig_DEFSHOOT_BOWMAN();
#define DEFSHOOT_BOWMAN (RuntimeConfig_DEFSHOOT_BOWMAN())

int RuntimeConfig_BLOOD_COMPOSITE_BOWMAN();
#define BLOOD_COMPOSITE_BOWMAN (RuntimeConfig_BLOOD_COMPOSITE_BOWMAN())

Double RuntimeConfig_SPEED_COMPOSITE_BOWMAN();
#define SPEED_COMPOSITE_BOWMAN (RuntimeConfig_SPEED_COMPOSITE_BOWMAN())

int RuntimeConfig_VISION_COMPOSITE_BOWMAN();
#define VISION_COMPOSITE_BOWMAN (RuntimeConfig_VISION_COMPOSITE_BOWMAN())

int RuntimeConfig_ATK_COMPOSITE_BOWMAN();
#define ATK_COMPOSITE_BOWMAN (RuntimeConfig_ATK_COMPOSITE_BOWMAN())

Double RuntimeConfig_DIS_COMPOSITE_BOWMAN();
#define DIS_COMPOSITE_BOWMAN (RuntimeConfig_DIS_COMPOSITE_BOWMAN())

Double RuntimeConfig_INTERVAL_COMPOSITE_BOWMAN();
#define INTERVAL_COMPOSITE_BOWMAN (RuntimeConfig_INTERVAL_COMPOSITE_BOWMAN())

int RuntimeConfig_DEFCLOSE_COMPOSITE_BOWMAN();
#define DEFCLOSE_COMPOSITE_BOWMAN (RuntimeConfig_DEFCLOSE_COMPOSITE_BOWMAN())

int RuntimeConfig_DEFSHOOT_COMPOSITE_BOWMAN();
#define DEFSHOOT_COMPOSITE_BOWMAN (RuntimeConfig_DEFSHOOT_COMPOSITE_BOWMAN())

int RuntimeConfig_NOWRES_TIMER_COMPOSITE_BOWMAN();
#define NOWRES_TIMER_COMPOSITE_BOWMAN (RuntimeConfig_NOWRES_TIMER_COMPOSITE_BOWMAN())

int RuntimeConfig_BLOOD_CHARIOT_ARCHER();
#define BLOOD_CHARIOT_ARCHER (RuntimeConfig_BLOOD_CHARIOT_ARCHER())

Double RuntimeConfig_SPEED_CHARIOT_ARCHER();
#define SPEED_CHARIOT_ARCHER (RuntimeConfig_SPEED_CHARIOT_ARCHER())

int RuntimeConfig_VISION_CHARIOT_ARCHER();
#define VISION_CHARIOT_ARCHER (RuntimeConfig_VISION_CHARIOT_ARCHER())

int RuntimeConfig_ATK_CHARIOT_ARCHER();
#define ATK_CHARIOT_ARCHER (RuntimeConfig_ATK_CHARIOT_ARCHER())

Double RuntimeConfig_DIS_CHARIOT_ARCHER();
#define DIS_CHARIOT_ARCHER (RuntimeConfig_DIS_CHARIOT_ARCHER())

Double RuntimeConfig_INTERVAL_CHARIOT_ARCHER();
#define INTERVAL_CHARIOT_ARCHER (RuntimeConfig_INTERVAL_CHARIOT_ARCHER())

int RuntimeConfig_DEFCLOSE_CHARIOT_ARCHER();
#define DEFCLOSE_CHARIOT_ARCHER (RuntimeConfig_DEFCLOSE_CHARIOT_ARCHER())

int RuntimeConfig_DEFSHOOT_CHARIOT_ARCHER();
#define DEFSHOOT_CHARIOT_ARCHER (RuntimeConfig_DEFSHOOT_CHARIOT_ARCHER())

int RuntimeConfig_NOWRES_TIMER_CHARIOT_ARCHER();
#define NOWRES_TIMER_CHARIOT_ARCHER (RuntimeConfig_NOWRES_TIMER_CHARIOT_ARCHER())

int RuntimeConfig_BLOOD_IMPROVEDBOWMAN1();
#define BLOOD_IMPROVEDBOWMAN1 (RuntimeConfig_BLOOD_IMPROVEDBOWMAN1())

Double RuntimeConfig_SPEED_IMPROVEDBOWMAN1();
#define SPEED_IMPROVEDBOWMAN1 (RuntimeConfig_SPEED_IMPROVEDBOWMAN1())

int RuntimeConfig_VISION_IMPROVEDBOWMAN1();
#define VISION_IMPROVEDBOWMAN1 (RuntimeConfig_VISION_IMPROVEDBOWMAN1())

int RuntimeConfig_DIS_IMPROVEDBOWMAN1();
#define DIS_IMPROVEDBOWMAN1 (RuntimeConfig_DIS_IMPROVEDBOWMAN1())

Double RuntimeConfig_INTERVAL_IMPROVEDBOWMAN1();
#define INTERVAL_IMPROVEDBOWMAN1 (RuntimeConfig_INTERVAL_IMPROVEDBOWMAN1())

int RuntimeConfig_ATK_IMPROVEDBOWMAN1();
#define ATK_IMPROVEDBOWMAN1 (RuntimeConfig_ATK_IMPROVEDBOWMAN1())

int RuntimeConfig_DEFCLOSE_IMPROVEDBOWMAN1();
#define DEFCLOSE_IMPROVEDBOWMAN1 (RuntimeConfig_DEFCLOSE_IMPROVEDBOWMAN1())

int RuntimeConfig_DEFSHOOT_IMPROVEDBOWMAN1();
#define DEFSHOOT_IMPROVEDBOWMAN1 (RuntimeConfig_DEFSHOOT_IMPROVEDBOWMAN1())

int RuntimeConfig_BLOOD_IMPROVEDBOWMAN2();
#define BLOOD_IMPROVEDBOWMAN2 (RuntimeConfig_BLOOD_IMPROVEDBOWMAN2())

Double RuntimeConfig_SPEED_IMPROVEDBOWMAN2();
#define SPEED_IMPROVEDBOWMAN2 (RuntimeConfig_SPEED_IMPROVEDBOWMAN2())

int RuntimeConfig_VISION_IMPROVEDBOWMAN2();
#define VISION_IMPROVEDBOWMAN2 (RuntimeConfig_VISION_IMPROVEDBOWMAN2())

int RuntimeConfig_DIS_IMPROVEDBOWMAN2();
#define DIS_IMPROVEDBOWMAN2 (RuntimeConfig_DIS_IMPROVEDBOWMAN2())

Double RuntimeConfig_INTERVAL_IMPROVEDBOWMAN2();
#define INTERVAL_IMPROVEDBOWMAN2 (RuntimeConfig_INTERVAL_IMPROVEDBOWMAN2())

int RuntimeConfig_ATK_IMPROVEDBOWMAN2();
#define ATK_IMPROVEDBOWMAN2 (RuntimeConfig_ATK_IMPROVEDBOWMAN2())

int RuntimeConfig_DEFCLOSE_IMPROVEDBOWMAN2();
#define DEFCLOSE_IMPROVEDBOWMAN2 (RuntimeConfig_DEFCLOSE_IMPROVEDBOWMAN2())

int RuntimeConfig_DEFSHOOT_IMPROVEDBOWMAN2();
#define DEFSHOOT_IMPROVEDBOWMAN2 (RuntimeConfig_DEFSHOOT_IMPROVEDBOWMAN2())

int RuntimeConfig_BLOOD_SCOUT();
#define BLOOD_SCOUT (RuntimeConfig_BLOOD_SCOUT())

Double RuntimeConfig_SPEED_SCOUT();
#define SPEED_SCOUT (RuntimeConfig_SPEED_SCOUT())

int RuntimeConfig_VISION_SCOUT();
#define VISION_SCOUT (RuntimeConfig_VISION_SCOUT())

int RuntimeConfig_DIS_SCOUT();
#define DIS_SCOUT (RuntimeConfig_DIS_SCOUT())

Double RuntimeConfig_INTERVAL_SCOUT();
#define INTERVAL_SCOUT (RuntimeConfig_INTERVAL_SCOUT())

int RuntimeConfig_ATK_SCOUT();
#define ATK_SCOUT (RuntimeConfig_ATK_SCOUT())

int RuntimeConfig_DEFCLOSE_SCOUT();
#define DEFCLOSE_SCOUT (RuntimeConfig_DEFCLOSE_SCOUT())

int RuntimeConfig_DEFSHOOT_SCOUT();
#define DEFSHOOT_SCOUT (RuntimeConfig_DEFSHOOT_SCOUT())

int RuntimeConfig_BLOOD_CHARIOT();
#define BLOOD_CHARIOT (RuntimeConfig_BLOOD_CHARIOT())

Double RuntimeConfig_SPEED_CHARIOT();
#define SPEED_CHARIOT (RuntimeConfig_SPEED_CHARIOT())

int RuntimeConfig_VISION_CHARIOT();
#define VISION_CHARIOT (RuntimeConfig_VISION_CHARIOT())

int RuntimeConfig_ATK_CHARIOT();
#define ATK_CHARIOT (RuntimeConfig_ATK_CHARIOT())

Double RuntimeConfig_DIS_CHARIOT();
#define DIS_CHARIOT (RuntimeConfig_DIS_CHARIOT())

Double RuntimeConfig_INTERVAL_CHARIOT();
#define INTERVAL_CHARIOT (RuntimeConfig_INTERVAL_CHARIOT())

int RuntimeConfig_DEFCLOSE_CHARIOT();
#define DEFCLOSE_CHARIOT (RuntimeConfig_DEFCLOSE_CHARIOT())

int RuntimeConfig_DEFSHOOT_CHARIOT();
#define DEFSHOOT_CHARIOT (RuntimeConfig_DEFSHOOT_CHARIOT())

int RuntimeConfig_NOWRES_TIMER_CHARIOT();
#define NOWRES_TIMER_CHARIOT (RuntimeConfig_NOWRES_TIMER_CHARIOT())

int RuntimeConfig_BLOOD_CAVALRY();
#define BLOOD_CAVALRY (RuntimeConfig_BLOOD_CAVALRY())

Double RuntimeConfig_SPEED_CAVALRY();
#define SPEED_CAVALRY (RuntimeConfig_SPEED_CAVALRY())

int RuntimeConfig_VISION_CAVALRY();
#define VISION_CAVALRY (RuntimeConfig_VISION_CAVALRY())

int RuntimeConfig_DIS_CAVALRY();
#define DIS_CAVALRY (RuntimeConfig_DIS_CAVALRY())

Double RuntimeConfig_INTERVAL_CAVALRY();
#define INTERVAL_CAVALRY (RuntimeConfig_INTERVAL_CAVALRY())

int RuntimeConfig_ATK_CAVALRY();
#define ATK_CAVALRY (RuntimeConfig_ATK_CAVALRY())

int RuntimeConfig_DEFCLOSE_CAVALRY();
#define DEFCLOSE_CAVALRY (RuntimeConfig_DEFCLOSE_CAVALRY())

int RuntimeConfig_DEFSHOOT_CAVALRY();
#define DEFSHOOT_CAVALRY (RuntimeConfig_DEFSHOOT_CAVALRY())

int RuntimeConfig_BLOOD_SHIP();
#define BLOOD_SHIP (RuntimeConfig_BLOOD_SHIP())

Double RuntimeConfig_SPEED_SHIP();
#define SPEED_SHIP (RuntimeConfig_SPEED_SHIP())

int RuntimeConfig_VISION_SHIP();
#define VISION_SHIP (RuntimeConfig_VISION_SHIP())

int RuntimeConfig_ATK_SHIP();
#define ATK_SHIP (RuntimeConfig_ATK_SHIP())

Double RuntimeConfig_DIS_SHIP();
#define DIS_SHIP (RuntimeConfig_DIS_SHIP())

int RuntimeConfig_INTERVAL_SHIP();
#define INTERVAL_SHIP (RuntimeConfig_INTERVAL_SHIP())

int RuntimeConfig_DEFCLOSE_SHIP();
#define DEFCLOSE_SHIP (RuntimeConfig_DEFCLOSE_SHIP())

int RuntimeConfig_DEFSHOOT_SHIP();
#define DEFSHOOT_SHIP (RuntimeConfig_DEFSHOOT_SHIP())

int RuntimeConfig_BLOOD_STONE_THROWER();
#define BLOOD_STONE_THROWER (RuntimeConfig_BLOOD_STONE_THROWER())

Double RuntimeConfig_SPEED_STONE_THROWER();
#define SPEED_STONE_THROWER (RuntimeConfig_SPEED_STONE_THROWER())

int RuntimeConfig_VISION_STONE_THROWER();
#define VISION_STONE_THROWER (RuntimeConfig_VISION_STONE_THROWER())

int RuntimeConfig_ATK_STONE_THROWER();
#define ATK_STONE_THROWER (RuntimeConfig_ATK_STONE_THROWER())

Double RuntimeConfig_DIS_STONE_THROWER();
#define DIS_STONE_THROWER (RuntimeConfig_DIS_STONE_THROWER())

Double RuntimeConfig_DIS_MIN_STONE_THROWER();
#define DIS_MIN_STONE_THROWER (RuntimeConfig_DIS_MIN_STONE_THROWER())

int RuntimeConfig_INTERVAL_STONE_THROWER();
#define INTERVAL_STONE_THROWER (RuntimeConfig_INTERVAL_STONE_THROWER())

int RuntimeConfig_DEFCLOSE_STONE_THROWER();
#define DEFCLOSE_STONE_THROWER (RuntimeConfig_DEFCLOSE_STONE_THROWER())

int RuntimeConfig_DEFSHOOT_STONE_THROWER();
#define DEFSHOOT_STONE_THROWER (RuntimeConfig_DEFSHOOT_STONE_THROWER())

int RuntimeConfig_BLOOD_PRIEST();
#define BLOOD_PRIEST (RuntimeConfig_BLOOD_PRIEST())

Double RuntimeConfig_SPEED_PRIEST();
#define SPEED_PRIEST (RuntimeConfig_SPEED_PRIEST())

int RuntimeConfig_VISION_PRIEST();
#define VISION_PRIEST (RuntimeConfig_VISION_PRIEST())

int RuntimeConfig_ATK_PRIEST();
#define ATK_PRIEST (RuntimeConfig_ATK_PRIEST())

Double RuntimeConfig_DIS_PRIEST();
#define DIS_PRIEST (RuntimeConfig_DIS_PRIEST())

Double RuntimeConfig_INTERVAL_PRIEST();
#define INTERVAL_PRIEST (RuntimeConfig_INTERVAL_PRIEST())

int RuntimeConfig_DEFCLOSE_PRIEST();
#define DEFCLOSE_PRIEST (RuntimeConfig_DEFCLOSE_PRIEST())

int RuntimeConfig_DEFSHOOT_PRIEST();
#define DEFSHOOT_PRIEST (RuntimeConfig_DEFSHOOT_PRIEST())

Double RuntimeConfig_Missile_Speed_Spear();
#define Missile_Speed_Spear (RuntimeConfig_Missile_Speed_Spear())

Double RuntimeConfig_Missile_Speed_Arrow();
#define Missile_Speed_Arrow (RuntimeConfig_Missile_Speed_Arrow())

Double RuntimeConfig_Missile_Speed_Cobblestone();
#define Missile_Speed_Cobblestone (RuntimeConfig_Missile_Speed_Cobblestone())

Double RuntimeConfig_Missile_Speed_Boulders();
#define Missile_Speed_Boulders (RuntimeConfig_Missile_Speed_Boulders())

Double RuntimeConfig_Missile_Boulders_Range();
#define Missile_Boulders_Range (RuntimeConfig_Missile_Boulders_Range())

int RuntimeConfig_NOWRES_TIMER_FARMER();
#define NOWRES_TIMER_FARMER (RuntimeConfig_NOWRES_TIMER_FARMER())

int RuntimeConfig_NOWRES_TIMER_CLUBMAN();
#define NOWRES_TIMER_CLUBMAN (RuntimeConfig_NOWRES_TIMER_CLUBMAN())

int RuntimeConfig_NOWRES_TIMER_BOWMAN();
#define NOWRES_TIMER_BOWMAN (RuntimeConfig_NOWRES_TIMER_BOWMAN())

int RuntimeConfig_NOWRES_TIMER_IMPROVEDBOWMAN1();
#define NOWRES_TIMER_IMPROVEDBOWMAN1 (RuntimeConfig_NOWRES_TIMER_IMPROVEDBOWMAN1())

int RuntimeConfig_NOWRES_TIMER_SCOUT();
#define NOWRES_TIMER_SCOUT (RuntimeConfig_NOWRES_TIMER_SCOUT())

int RuntimeConfig_NOWRES_TIMER_CAVALRY();
#define NOWRES_TIMER_CAVALRY (RuntimeConfig_NOWRES_TIMER_CAVALRY())

int RuntimeConfig_NOWRES_TIMER_SLINGER();
#define NOWRES_TIMER_SLINGER (RuntimeConfig_NOWRES_TIMER_SLINGER())

int RuntimeConfig_NOWRES_TIMER_SWORSMAN();
#define NOWRES_TIMER_SWORSMAN (RuntimeConfig_NOWRES_TIMER_SWORSMAN())

int RuntimeConfig_NOWRES_TIMER_LION();
#define NOWRES_TIMER_LION (RuntimeConfig_NOWRES_TIMER_LION())

int RuntimeConfig_NOWRES_TIMER_ELEPHANT();
#define NOWRES_TIMER_ELEPHANT (RuntimeConfig_NOWRES_TIMER_ELEPHANT())

int RuntimeConfig_NOWRES_TIMER_SHIP();
#define NOWRES_TIMER_SHIP (RuntimeConfig_NOWRES_TIMER_SHIP())

int RuntimeConfig_NOWRES_TIMER_STONE_THROWER();
#define NOWRES_TIMER_STONE_THROWER (RuntimeConfig_NOWRES_TIMER_STONE_THROWER())

int RuntimeConfig_NOWRES_TIMER_PRIEST();
#define NOWRES_TIMER_PRIEST (RuntimeConfig_NOWRES_TIMER_PRIEST())

int RuntimeConfig_PRIEST_REST_TIME();
#define PRIEST_REST_TIME (RuntimeConfig_PRIEST_REST_TIME())

int RuntimeConfig_BLOOD_HOPLITE();
#define BLOOD_HOPLITE (RuntimeConfig_BLOOD_HOPLITE())

Double RuntimeConfig_SPEED_HOPLITE();
#define SPEED_HOPLITE (RuntimeConfig_SPEED_HOPLITE())

int RuntimeConfig_VISION_HOPLITE();
#define VISION_HOPLITE (RuntimeConfig_VISION_HOPLITE())

int RuntimeConfig_ATK_HOPLITE();
#define ATK_HOPLITE (RuntimeConfig_ATK_HOPLITE())

Double RuntimeConfig_DIS_HOPLITE();
#define DIS_HOPLITE (RuntimeConfig_DIS_HOPLITE())

Double RuntimeConfig_INTERVAL_HOPLITE();
#define INTERVAL_HOPLITE (RuntimeConfig_INTERVAL_HOPLITE())

int RuntimeConfig_DEFCLOSE_HOPLITE();
#define DEFCLOSE_HOPLITE (RuntimeConfig_DEFCLOSE_HOPLITE())

int RuntimeConfig_DEFSHOOT_HOPLITE();
#define DEFSHOOT_HOPLITE (RuntimeConfig_DEFSHOOT_HOPLITE())

int RuntimeConfig_NOWRES_TIMER_HOPLITE();
#define NOWRES_TIMER_HOPLITE (RuntimeConfig_NOWRES_TIMER_HOPLITE())

int RuntimeConfig_Boulder_Trail_Effect_Duration();
#define Boulder_Trail_Effect_Duration (RuntimeConfig_Boulder_Trail_Effect_Duration())

int RuntimeConfig_DefaultCivilization();
#define DefaultCivilization (RuntimeConfig_DefaultCivilization())

int RuntimeConfig_EnemyTechnologyMaxCivilization();
#define EnemyTechnologyMaxCivilization (RuntimeConfig_EnemyTechnologyMaxCivilization())

bool RuntimeConfig_OffScreen();
#define OffScreen (RuntimeConfig_OffScreen())

Double RuntimeConfig_MUSIC_VOLUME();
#define MUSIC_VOLUME (RuntimeConfig_MUSIC_VOLUME())

bool RuntimeConfig_isPlayerBuildingDisabled(int buildingNum);
#define isPlayerBuildingDisabled(b) (RuntimeConfig_isPlayerBuildingDisabled(b))

void ApplyRuntimeConfigFromJson(const QJsonObject& config);

#endif // RUNTIMECONFIG_H
